use_frameworks!

platform :ios, '8.0'

target 'LSSStickersManage_Example' do
  pod 'LSSStickersManage', :path => '../'

  target 'LSSStickersManage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
